services:
  - type: web
    name: tasknova-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
      - key: GEMINI_API_KEY